kind: ConfigMap
apiVersion: v1
metadata:
  name: fancave-model-players-config
data:
  model-config.json: |
    {
      "_meta": {
        "sources": [
          "loopback/common/models",
          "loopback/server/models",
          "../common/models",
          "./models"
        ],
        "mixins": [
          "loopback/common/mixins",
          "loopback/server/mixins",
          "../common/mixins",
          "./mixins"
        ]
      },
      "Team": {
        "dataSource": "in-memory",
        "public": false
      },
      "Player": {
        "dataSource": "in-memory",
        "public": true
      },
      "News": {
        "dataSource": "in-memory",
        "public": false
      }
    }
