apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: players
  name: fancave-players
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
      - image: ozairs/fancave-server:v1
        name: fancave-players
        ports:
        - containerPort: 3080
        volumeMounts:
        - mountPath: /usr/src/app/server/datasources.json
          subPath: datasources.json
          name: fancave-ds
        - mountPath: /usr/src/app/server/model-config.json
          subPath: model-config.json
          name: fancave-model
        readinessProbe:
          tcpSocket:
            port: 3080
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 3080
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: fancave-ds
        configMap:
          name: fancave-ds-players-config
      - name: fancave-model
        configMap:
          name: fancave-model-players-config
