kind: ConfigMap
apiVersion: v1
metadata:
  name: fancave-ui-configmap
data:
  fancave.conf: "  server {\n    listen 80 default_server;\n   \tlisten [::]:80 default_server;\n
    \   #listen 443 ssl;\n   \t#listen [::]:443 ssl;\n\t  \n    #server_name fancave;\n
    \   root /var/www/fancave;\n\n    index index.html;\n\n    ssl_certificate           /etc/nginx/cert.pem;\n
    \   ssl_certificate_key       /etc/nginx/key.pem;\n    ssl_session_cache builtin:1000
    shared:SSL:10m;\n    ssl_protocols TLSv1.2;\n    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;\n
    \   ssl_prefer_server_ciphers on;\n\n    gzip on;\n    gzip_types application/javascript
    image/* text/css;\n    gunzip on;\n\n    location /api/team/ {\n      proxy_set_header
    \       Host $host;\n        proxy_set_header        X-Real-IP $remote_addr;\n
    \       proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       proxy_set_header        X-Forwarded-Proto $scheme;\n\n        proxy_pass
    \ PROTOCOL://TEAMS_SERVER;\n        proxy_read_timeout  60;\n    }\n\n    location
    /api/news/ {\n      proxy_set_header        Host $host;\n        proxy_set_header
    \       X-Real-IP $remote_addr;\n        proxy_set_header        X-Forwarded-For
    $proxy_add_x_forwarded_for;\n        proxy_set_header        X-Forwarded-Proto
    $scheme;\n\n        proxy_pass  PROTOCOL://NEWS_SERVER;\n        proxy_read_timeout
    \ 60;\n    }\n\n    location /api/player/ {\n      proxy_set_header        Host
    $host;\n        proxy_set_header        X-Real-IP $remote_addr;\n        proxy_set_header
    \       X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header
    \       X-Forwarded-Proto $scheme;\n\n        proxy_pass  PROTOCOL://PLAYERS_SERVER;\n
    \       proxy_read_timeout  60;\n    }\n\n    location ~* \\.(jpg|jpeg|png|gif|ico)$
    {\n        expires 30d;\n    }\n      \n    location ~* \\.(css|js)$ {\n        expires
    7d;\n    }\n  \n    location /fancave/ {\n    \n      try_files $uri /index.html;\n
    \       \n      proxy_set_header        Host $host;\n      proxy_set_header        X-Real-IP
    $remote_addr;\n      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \     proxy_set_header        X-Forwarded-Proto $scheme;\n\n      proxy_read_timeout
    \ 60;\n    }\n\n  }"
