---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: yahoo-sports-egress
spec:
  destination:
    service: sports.yahoo.com
  ports:
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: yahoo-login-egress
spec:
  destination:
    service: api.login.yahoo.com
  ports:
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: yahoo-query-egress
spec:
  destination:
    service: query.yahooapis.com
  ports:
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: yahoo-fsports-egress
spec:
  destination:
    service: fantasysports.yahooapis.com
  ports:
    - port: 443
      protocol: https